### ISSUE TITLE
Add big plan to readme 

### ISSUE THREAD

**Issue by rom1504** [LAION-AI/the-big-plan#1]
Goal of this repo: give a vision to Laion. Inspire people. Make it easy to understand why each project is important and how it contributes to the overall goal.

In practice:
* Iterate on a gdoc
* Commit as a .md

I'll do a first proposal soon.

**Comment by robvanvolt** [comment]
Sounds interesting! 👍

**Comment by robvanvolt** [comment]
I'd start with

- Making AI not only open, but also accesible and transparent for the people (by good documentation, easy to start training setups etc.)
- Multimodal "everything-to-everything" models as a preparation for general AI with the help of previous, more-specific mutlimodal models/methods for the greater good

**Comment by rom1504** [comment]
https://docs.google.com/document/d/1gRgYhMQpVrmUf3wOwFrc-Z3cNCkVUkCGetTnEEOrRmg/edit?usp=sharing

https://github.com/LAION-AI/the-big-plan

my proposal

let's iterate over it :)
